### ISSUE TITLE
Add support for DbDataAdapter

### ISSUE THREAD

**Issue by R0Wi** [Apps72/DbMocker#24]
Hi and thank you for this amazing library,

we use your components a lot to mock our database connections and they work very well. But we have some code that's using the  `DbDataAdapter` class for reading data like this:

```cs
var dt = new DataTable();
using (var cmd = connection.CreateCommand())
{
    cmd.CommandText = "SELECT * FROM MYTABLE";
    using (var dataAdapter = new MyDbDataAdapter())
    {
        dataAdapter.SelectCommand = cmd;
        dataAdapter.Fill(dt);
    }
}
```

Unfortunately i didn't find anything in the docs regarding the `DbDataAdapter`. Are there any possibilities to test these kinds of code or must the library be extended?

Thank you!

**Comment by dvoituron** [comment]
Hello. 

DbAdapter is to fill a Dataset or DataTable. So, you can use the method ReturnsTable.

Is it solve you question?

**Comment by R0Wi** [comment]
Perfect that works, thanks ! 👍 

I just had to inherit the `DbDataAdaper` baseclass (without any additional implementation inside). Then that DataAdapter worked on the faked Command object and the data is returned successfully.

**Comment by dvoituron** [comment]
Great,

Do you have a sample code to let me see what I could add in DbMocker to simplify this treatment?

**Comment by R0Wi** [comment]
Well i don't think that there is anything to do inside your library, the only thing i could imagine ist updating the docs. Basically inside the tests we have to ensure that the `DbDataAdapter` is working on our faked `MockDbCommand` object then everything works as expected. Since we're connected do a Oracle database our code looks something like this:

```cs
public class MyDataLoader()
{
        public DataTable LoadData()
        {
            using (var connection = new OracleConnection(...))
            using (var dataAdapter = new OracleDataAdapter())
            {
                return LoadData(connection, dataAdapter);
            }
        }
        
        public DataTable LoadData(IDbConnection connection, IDbDataAdapter dataAdapter)
        {
            var dt = new DataTable();
            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = "SELECT SOMETHING FROM MYTABLE";
                dataAdapter.SelectCommand = cmd;
                dataAdapter.Fill(dt);
            }
            return dt;
        }
}
```

An empty `DbDataAdapter` implementation just using the base class code in .NET Framework:

```cs
public FakeDbDataAdapter : DbDataAdapter { }
```

And then the test:

```cs
[TestMethod]
public void UnitTest1()
{
    var conn = new MockDbConnection();

    conn.Mocks
        .When(cmd => cmd.CommandText == "SELECT SOMETHING FROM MYTABLE")
        .ReturnsTable(MockTable.WithColumns("SOMETHING")
                               .AddRow("SOMEVALUE"));

  var loader = new MyDataLoader();
  var dt = loader.LoadData(conn, new FakeDbDataAdapter());
}
```

Actually this is not our real production code since we're using our own ADO.NET wrapper classes but i think it's a sample showing the way to go.
