### ISSUE TITLE
IsClosed on reader does not return true

### ISSUE THREAD

**Issue by kiainlogicdk** [Apps72/DbMocker#32]
When running a sql mocked command myReader.IsClosed never returns true.
It does not matter if you have multiple Select statements in the query or just one.
ReturnDataset or ReturnTable makes no difference

Full project example can be found here.
[MockSQL.zip](https://github.com/Apps72/DbMocker/files/10906759/MockSQL.zip)

using (var myReader = await SQLCmd.ExecuteReaderAsync())
{
    do
    {
        var dataTable = new DataTable();
        dataTable.Load(myReader);
        dataSet.Tables.Add(dataTable);
    }
    while (myReader.IsClosed == false);
}

**Comment by kiainlogicdk** [comment]
anything happening?

**Comment by dvoituron** [comment]
Sorry, I was busy with other projects and forgot about this one. I'll have a look this week

**Comment by dvoituron** [comment]
How did you see this? I suggest adding a method `MockDbDataReader.Close(bool value)` to update the `IsClosed` property.

**Comment by kiainlogicdk** [comment]
if i put a close line below dataSet.Tables.Add(dataTable); then it won't read anymore tables from my SQL Query.
This would break my loop functionality. I should not need to know how many datatables are in my SQL query.
This loop works with standard SQL client not being mocked.

Or did i not understand your suggestion 😊

**Comment by dvoituron** [comment]
Exactly, you could use...

``` csharp
using (var myReader = await SQLCmd.ExecuteReaderAsync())
{
    do
    {
        var dataTable = new DataTable();
        dataTable.Load(myReader);
        dataSet.Tables.Add(dataTable);

        if (myCondition)   
        {
             myReader.Close(true);  // New line
        }
    }
    while (myReader.IsClosed == false);
}
```

**Comment by kiainlogicdk** [comment]
but the condition should be handled by mock when seing there is not more datatables in the SQL query.
If i say 

Select  * from Persons Where id = 1
Select  * from Persons Where id = 2

It should automatically close the reader after second loop at the line  dataSet.Tables.Add(dataTable);. I should not have to make a condition check. My condition check is this line  while (myReader.IsClosed == false);

**Comment by dvoituron** [comment]
I don't actually execute the query, so I don't know when the query is "finished".
You'll need to tell DbMock when to close this connection.

**Comment by kiainlogicdk** [comment]
But if my condition is reading the final datatable in SQL query. How can i see the number of datatables in a SQL query.
I use the work around but its not pretty.

`  
//Mock SQL since myReader.IsClosed does not work
  var myReader = SQLCmd.ExecuteReader();
  dataSet = new DataSet();
  dataSet.Load(myReader, LoadOption.PreserveChanges, new string[1000]);
  myReader.Close();

  //remove DataTables without columns
  var count = 0;
  var loopCount = dataSet.Tables.Count;
  for (int i = 0; i < loopCount; i++)
  {
      if (dataSet.Tables[count].Columns.Count == 0)
      {
          dataSet.Tables.RemoveAt(count);
      }
      else
      {
          count++;
      }
  }
`

**Comment by dvoituron** [comment]
Looking at your first example in more detail, I don't understand why you don't use the `myReader.NextResult()` method. Because you need to use this method to go to the results of the second request. And this method returns a boolean (true if there are other results).

What's more, the `Close()` method already exists in `DbDataReader`. There's no point in adding a new `Close` method.

**Comment by kiainlogicdk** [comment]
since  dataTable.Load(myReader); automatically advances the reader to the next result. This means calling nextresult moves the cursor 2 times and causes it to skip tables.  dataTable.Load does not return a bool to check for more data 😠

**Comment by kiainlogicdk** [comment]
mock does not advance the reader when dataTable.Load and there is no more table. It should check and close the reader.

**Comment by dvoituron** [comment]
Let me check to know how the DataTable.Load calls the DataReader.

**Comment by dvoituron** [comment]
I found a solution.
Package is publishing: https://www.nuget.org/packages/DbMocker/1.23.0

**Comment by kiainlogicdk** [comment]
Thank you. Worked like a charm 😊
